[notebook]
exclude = ["templates/"]

[note]
filename = "{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 0

[extra]
author = "Chris"

[tool]
pager = "cat"
fzf-preview = "bat --color=always --style=plain --theme=TwoDark /brain/{}"

[filter]
recents = "--sort created- --created-after '2 weeks ago'"
