#!/bin/sh
# Idempotently seed Claude Code user config from the baked-in seed directory.
# Files are only written on first run — edits in the volume survive rebuilds.
# ~/.claude.json lives inside the volume and is symlinked from the home dir
# so Claude Code can write session state without clobbering it on rebuild.

# Load vault-level env overrides (generated by brain-init or created manually).
# Container env vars (from docker run -e or docker-compose env_file) take
# precedence because they are already set; this only fills in unset vars.
if [ -f /brain/.env ]; then
    set -a
    . /brain/.env
    set +a
fi

# If the user explicitly invoked brain-init, run it directly (interactive wizard).
# Skip the rest of the entrypoint so code-server doesn't start on top.
if [ "$1" = "brain-init" ]; then
    shift
    exec brain-init "$@"
fi

CLAUDE_DIR=/home/coder/.claude
SEED_DIR=/usr/local/lib/brain-tools/claude-seed
mkdir -p "$CLAUDE_DIR"
# Seed visible files/dirs (settings.json, skills/, agents/, etc.)
for f in "$SEED_DIR"/*; do
    dest="$CLAUDE_DIR/$(basename "$f")"
    [ ! -e "$dest" ] && cp -r "$f" "$dest"
done
# Seed dotfiles separately (glob * skips them in sh)
if [ ! -f "$CLAUDE_DIR/.claude.json" ]; then
    cp "$SEED_DIR/.claude.json" "$CLAUDE_DIR/.claude.json"
fi
# Symlink ~/.claude.json → volume so Claude Code session writes persist
ln -sf "$CLAUDE_DIR/.claude.json" /home/coder/.claude.json

# Auto-initialise the vault on first mount (non-interactive defaults).
# This ensures .zk/, .ai/, .vscode/, and vault skills are always present
# without the user needing to remember to run brain-init manually.
if [ -d /brain ] && [ ! -d /brain/.zk ]; then
    brain-init --auto
fi

# Start brain background services, then hand off to code-server.
#
# The watcher requires only the embedding model to be reachable — it has
# no dependency on brain-init or zk. If the model is not yet available,
# the watcher will retry every 30 seconds until it connects.
if [ -d /brain ]; then
    mkdir -p /brain/.ai
    (
        RETRY_DELAY=30
        while true; do
            brain-index watch >> /brain/.ai/watch.log 2>&1
            EXIT_CODE=$?
            if [ "$EXIT_CODE" -eq 1 ]; then
                echo "$(date): brain-index watch exited with error (code $EXIT_CODE) — not retrying. Check watch.log for details." >> /brain/.ai/watch.log
                break
            fi
            echo "$(date): brain-index watch exited (code $EXIT_CODE), retrying in ${RETRY_DELAY}s..." >> /brain/.ai/watch.log
            sleep "$RETRY_DELAY"
        done
    ) &
    # Start the REST API server (unless explicitly disabled)
    if [ "${BRAIN_API_DISABLED:-}" != "1" ]; then
        brain-api >> /brain/.ai/api.log 2>&1 &
    fi
    # Optionally start the MCP server in HTTP mode for remote MCP clients
    if [ "${BRAIN_MCP_TRANSPORT:-}" = "http" ]; then
        BRAIN_MCP_TRANSPORT=http brain-mcp-server >> /brain/.ai/mcp-http.log 2>&1 &
    fi
fi
# Hand off to code-server's entrypoint (passes "$@" = "--auth none /brain")
exec /usr/bin/entrypoint.sh "$@"
