#!/bin/sh
# Shared setup logic sourced by both entrypoints (base and UI).
# Idempotently seeds Claude Code user config, auto-inits the vault,
# and starts background services. Does NOT start brain-api.

: "${BRAIN_DIR:=/brain}"
: "${CLAUDE_DIR:=/home/coder/.claude}"
: "${SEED_DIR:=/usr/local/lib/brain-tools/claude-seed}"

# Refresh ~/.claude/skills from the resolved profile (<brain>/.brain/skills/),
# not the image. brain-init --auto must have already staged the profile.
# These are not user-edited, so always overwrite.
seed_skills_from_profile() {
    rm -rf "$CLAUDE_DIR/skills"
    mkdir -p "$CLAUDE_DIR/skills"
    for tier in global vault; do
        src="$BRAIN_DIR/.brain/skills/$tier"
        [ -d "$src" ] || continue
        for skill in "$src"/*; do
            [ -e "$skill" ] || continue
            cp -r "$skill" "$CLAUDE_DIR/skills/$(basename "$skill")"
        done
    done
}

# Seed non-skill Claude Code config (settings.json, .claude.json, agents/, etc.)
# from the image SEED_DIR. Existing files are left intact so user config
# survives restarts.
seed_non_skill_config() {
    mkdir -p "$CLAUDE_DIR"
    for f in "$SEED_DIR"/*; do
        base=$(basename "$f")
        [ "$base" = "skills" ] && continue      # skills come from the profile
        dest="$CLAUDE_DIR/$base"
        [ ! -e "$dest" ] && cp -r "$f" "$dest"
    done
    # Seed dotfiles separately (glob * skips them in sh)
    [ -f "$CLAUDE_DIR/.claude.json" ] || cp "$SEED_DIR/.claude.json" "$CLAUDE_DIR/.claude.json"
    # Symlink ~/.claude.json → volume so Claude Code session writes persist
    ln -sf "$CLAUDE_DIR/.claude.json" /home/coder/.claude.json 2>/dev/null || true
}

# Test hook: seed skills only, then stop. Env-gated so it works under dash
# (the container's /bin/sh), which does not propagate args to a sourced file.
if [ "${SETUP_SEED_SKILLS_ONLY:-}" = "1" ]; then
    seed_skills_from_profile
    exit 0
fi

# Load vault-level env (generated by brain-init or created manually).
# These override any matching container env vars — vault config is authoritative
# for brain settings. Use docker run -e for settings not in the vault .env.
if [ -f "$BRAIN_DIR/.env" ]; then
    set -a
    . "$BRAIN_DIR/.env"
    set +a
fi

seed_non_skill_config

# Auto-initialise / update the vault (non-interactive defaults), then seed
# skills from the resolved profile. Runs on every start so vault skills,
# plugin staging, and hooks stay current after image upgrades. brain-init
# is idempotent.
if [ -d "$BRAIN_DIR" ]; then
    brain-init --auto
    seed_skills_from_profile
fi

# Start brain background services.
#
# The watcher requires only the embedding model to be reachable — it has
# no dependency on brain-init or zk. If the model is not yet available,
# the watcher will retry every 30 seconds until it connects.
if [ -d "$BRAIN_DIR" ]; then
    mkdir -p "$BRAIN_DIR/.ai"
    (
        RETRY_DELAY=30
        while true; do
            brain-index watch >> "$BRAIN_DIR/.ai/watch.log" 2>&1
            EXIT_CODE=$?
            echo "$(date): brain-index watch exited (code $EXIT_CODE), retrying in ${RETRY_DELAY}s..." >> "$BRAIN_DIR/.ai/watch.log"
            sleep "$RETRY_DELAY"
        done
    ) &
    # Optionally start the MCP server in HTTP mode for remote MCP clients
    if [ "${BRAIN_MCP_TRANSPORT:-}" = "http" ]; then
        BRAIN_MCP_TRANSPORT=http brain-mcp-server >> "$BRAIN_DIR/.ai/mcp-http.log" 2>&1 &
    fi
fi
