#!/bin/sh
# Shared setup logic sourced by both entrypoints (base and UI).
# Idempotently seeds Claude Code user config, auto-inits the vault,
# and starts background services. Does NOT start brain-api.

# Load vault-level env (generated by brain-init or created manually).
# These override any matching container env vars — vault config is authoritative
# for brain settings. Use docker run -e for settings not in the vault .env.
if [ -f /brain/.env ]; then
    set -a
    . /brain/.env
    set +a
fi

CLAUDE_DIR=/home/coder/.claude
SEED_DIR=/usr/local/lib/brain-tools/claude-seed
mkdir -p "$CLAUDE_DIR"
# In dev mode, force-resync skills on every restart so edits land without
# deleting the volume. Other seeded files (settings, .claude.json) are
# left intact so user config survives restarts.
if [ "${BRAIN_DEV:-0}" = "1" ]; then
    rm -rf "$CLAUDE_DIR/skills"
fi
# Seed visible files/dirs (settings.json, skills/, agents/, etc.)
for f in "$SEED_DIR"/*; do
    dest="$CLAUDE_DIR/$(basename "$f")"
    [ ! -e "$dest" ] && cp -r "$f" "$dest"
done
# Seed dotfiles separately (glob * skips them in sh)
if [ ! -f "$CLAUDE_DIR/.claude.json" ]; then
    cp "$SEED_DIR/.claude.json" "$CLAUDE_DIR/.claude.json"
fi
# Symlink ~/.claude.json → volume so Claude Code session writes persist
ln -sf "$CLAUDE_DIR/.claude.json" /home/coder/.claude.json

# Auto-initialise the vault on first mount (non-interactive defaults).
# This ensures .zk/, .ai/, .vscode/, and vault skills are always present
# without the user needing to remember to run brain-init manually.
if [ -d /brain ] && [ ! -d /brain/.zk ]; then
    brain-init --auto
fi

# Start brain background services.
#
# The watcher requires only the embedding model to be reachable — it has
# no dependency on brain-init or zk. If the model is not yet available,
# the watcher will retry every 30 seconds until it connects.
if [ -d /brain ]; then
    mkdir -p /brain/.ai
    (
        RETRY_DELAY=30
        while true; do
            brain-index watch >> /brain/.ai/watch.log 2>&1
            EXIT_CODE=$?
            echo "$(date): brain-index watch exited (code $EXIT_CODE), retrying in ${RETRY_DELAY}s..." >> /brain/.ai/watch.log
            sleep "$RETRY_DELAY"
        done
    ) &
    # Optionally start the MCP server in HTTP mode for remote MCP clients
    if [ "${BRAIN_MCP_TRANSPORT:-}" = "http" ]; then
        BRAIN_MCP_TRANSPORT=http brain-mcp-server >> /brain/.ai/mcp-http.log 2>&1 &
    fi
fi
